---
- hosts: Nexus Switches
  become: true
  tasks:
    - name: Backup Nexus Switches
      cisco.nxos.nxos_config:
      backup: true
      backup_options:
        filename: "backuptest.txt"
        dir_patch: /home/ccadmin
